/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fruitopia.view;

import fruitopia.model.Produk;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Asani
 */
public class ProdukPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProdukPanel
     */
    public ProdukPanel(Produk product) {
        initComponents();
        setPreferredSize(new Dimension(200, 250)); // Atur ukuran panel
        
        setLayout(new BorderLayout());

        // Gambar produk
        JLabel imageLabel = new JLabel();
        ImageIcon icon = new ImageIcon(product.getGambar());
        Image img = icon.getImage().getScaledInstance(180, 180, Image.SCALE_SMOOTH);
        imageLabel.setIcon(new ImageIcon(img));
        add(imageLabel, BorderLayout.NORTH);

        // Nama dan harga produk
        JPanel infoPanel = new JPanel(new GridLayout(2, 1));
        infoPanel.add(new JLabel(product.getNama(), SwingConstants.CENTER));
        infoPanel.add(new JLabel("Rp" + product.getHarga(), SwingConstants.CENTER));
        add(infoPanel, BorderLayout.CENTER);

        // Input jumlah dan tombol
        JPanel actionPanel = new JPanel(new BorderLayout());
        JSpinner qtySpinner = new JSpinner(new SpinnerNumberModel(1, 1, 100, 1));
        JButton button = new JButton("Beli");
        actionPanel.add(qtySpinner, BorderLayout.WEST);
        actionPanel.add(button, BorderLayout.EAST);
        add(actionPanel, BorderLayout.SOUTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
